[mypy]
ignore_missing_imports = True
disallow_untyped_defs = False
check_untyped_defs = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = False
namespace_packages = True

[mypy-tests.*]
ignore_errors = True
