"""Add skill columns to Project

Revision ID: 0d3446f2df76
Revises: aac66402b735
Create Date: 2026-06-12 10:33:09.769039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d3446f2df76'
down_revision: Union[str, Sequence[str], None] = 'aac66402b735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('main_languages', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('environments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'environments')
    op.drop_column('projects', 'skills')
    op.drop_column('projects', 'main_languages')
    # ### end Alembic commands ###
