"""fix schema

Revision ID: 25eaaa692760
Revises: 
Create Date: 2025-12-11 13:14:25.121671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25eaaa692760'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('affiliation_groups',
    # sa.Column('name', sa.String(), nullable=False),
    # sa.Column('id', sa.Uuid(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliation_group_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_departments_affiliation_groups', 'affiliation_groups', ['affiliation_group_id'], ['id'])

    with op.batch_alter_table('monthly_closings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('month', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('closed_by_id', sa.Uuid(), nullable=True))
        batch_op.create_unique_constraint('uq_monthly_closing_year_month', ['year', 'month'])
        batch_op.create_foreign_key('fk_monthly_closings_users', 'users', ['closed_by_id'], ['id'])
        batch_op.drop_column('year_month')
        batch_op.drop_column('created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_closings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('year_month', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint('fk_monthly_closings_users', type_='foreignkey')
        batch_op.drop_constraint('uq_monthly_closing_year_month', type_='unique')
        batch_op.drop_column('closed_by_id')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('month')
        batch_op.drop_column('year')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_departments_affiliation_groups', type_='foreignkey')
        batch_op.drop_column('affiliation_group_id')

    op.drop_table('affiliation_groups')
    # ### end Alembic commands ###
