"""Add hourly_rate to user

Revision ID: 2a1d7c636fef
Revises: 8ddd255f0cd9
Create Date: 2026-06-03 17:04:53.680022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1d7c636fef'
down_revision: Union[str, Sequence[str], None] = '8ddd255f0cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hourly_rate', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hourly_rate')
    # ### end Alembic commands ###
