"""Add project role

Revision ID: 33b1f50c310c
Revises: 0d3446f2df76
Create Date: 2026-06-12 02:02:50.085332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b1f50c310c'
down_revision: Union[str, Sequence[str], None] = '0d3446f2df76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_roles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_project_members_role_id', 'project_roles', ['role_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_members_role_id', type_='foreignkey')
        batch_op.drop_column('role_id')
    op.drop_table('project_roles')
    # ### end Alembic commands ###
