"""Add user_id to User

Revision ID: 40c2ff2543e3
Revises: 52f523s89h2
Create Date: 2026-01-08 17:20:37.800872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c2ff2543e3'
down_revision: Union[str, Sequence[str], None] = '52f523s89h2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.String(), nullable=True))
    with op.batch_alter_table('users') as batch_op:
        batch_op.create_unique_constraint('uq_users_user_id', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_user_id', 'users', type_='unique')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
