"""add settings to application template

Revision ID: 52f523s89h2
Revises: 25eaaa692760
Create Date: 2026-01-06 18:58:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52f523s89h2'
down_revision = '25eaaa692760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_templates', sa.Column('settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_templates', 'settings')
    # ### end Alembic commands ###
