"""add_difficulty_and_category_to_projects

Revision ID: 74e490ef0b95
Revises: 33b1f50c310c
Create Date: 2026-06-13 19:24:55.989092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74e490ef0b95'
down_revision: Union[str, Sequence[str], None] = '33b1f50c310c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'category')
    op.drop_column('projects', 'difficulty')
    # ### end Alembic commands ###
