"""Add leave types and ledgers

Revision ID: 8ddd255f0cd9
Revises: 294a7a977840
Create Date: 2026-06-01 23:09:39.100778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ddd255f0cd9'
down_revision: Union[str, Sequence[str], None] = '294a7a977840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('leave_ledgers',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('leave_type_id', sa.Uuid(), nullable=False),
    sa.Column('grant_date', sa.Date(), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=False),
    sa.Column('days_granted', sa.Float(), nullable=False),
    sa.Column('days_used', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Insert default system leave types and migrate existing paid leave ledger data
    import uuid
    paid_leave_uuid = uuid.uuid4()
    sub_leave_uuid = uuid.uuid4()

    # bulk insert leave types
    leave_types_table = sa.table(
        'leave_types',
        sa.column('id', sa.Uuid),
        sa.column('name', sa.String),
        sa.column('is_paid', sa.Boolean),
        sa.column('is_system', sa.Boolean)
    )
    op.bulk_insert(
        leave_types_table,
        [
            {'id': paid_leave_uuid, 'name': '有給休暇', 'is_paid': True, 'is_system': True},
            {'id': sub_leave_uuid, 'name': '代休', 'is_paid': True, 'is_system': True}
        ]
    )

    # Migrate data from paid_leave_ledgers to leave_ledgers
    # Standard SQL select-insert works on both SQLite and PostgreSQL.
    op.execute(
        f"INSERT INTO leave_ledgers (id, user_id, leave_type_id, grant_date, expire_date, days_granted, days_used) "
        f"SELECT id, user_id, '{str(paid_leave_uuid)}', grant_date, expire_date, days_granted, days_used "
        f"FROM paid_leave_ledgers"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave_ledgers')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
