"""Add status to shift

Revision ID: aac66402b735
Revises: 2a1d7c636fef
Create Date: 2026-06-03 17:36:17.193901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac66402b735'
down_revision: Union[str, Sequence[str], None] = '2a1d7c636fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('status', sa.String(), server_default='Approved', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'status')
    # ### end Alembic commands ###
