# HRConnect Backend Constants

# Work Rule Defaults
DEFAULT_ROUNDING_RULE_MINUTES = 15
DEFAULT_AUTO_BREAK_DEDUCTION_MINUTES = 60
DEFAULT_LATE_GRACE_PERIOD_MINUTES = 5

# System Defaults
DEFAULT_WORK_START_TIME = "09:00"
DEFAULT_WORK_END_TIME = "18:00"

# Half-day Leave Defaults
DEFAULT_HALF_DAY_MORNING_START = "09:00"
DEFAULT_HALF_DAY_MORNING_END = "12:00"
DEFAULT_HALF_DAY_AFTERNOON_START = "13:00"
DEFAULT_HALF_DAY_AFTERNOON_END = "18:00"
